coverage:
  status:
    project:
      default:
        target: auto
    patch: yes

  # Exclude mock files from coverage calculation
  ignore:
    - '**/mocks/**'
    - '**/mock/**'
    - '**/*_mock.go'
    - '**/*mock*.go'
    - '**/database/utils.go'
    - '**/cmd/api/**'
    - 'cmd/api/**'
    - '**/pkg/tracing/**'
    - '**/pkg/logger/testing.go'
    - '**/http/middleware/tracing.go'
    - '**/internal/tracing/**'
    - '**/tests/**'
    - '**/tests/**'
    - '**/testutil/**'
