# Google Cloud Function configuration
# This file can be used with Infrastructure as Code tools like Terraform

name: notifuse-telemetry
description: 'Receives anonymous telemetry data from Notifuse platform and logs it to Google Cloud Logging'
runtime: go124
entry_point: ReceiveTelemetry
trigger:
  type: http
  allow_unauthenticated: true
resources:
  memory: 256MB
  timeout: 30s
  max_instances: 10
environment_variables:
  GCP_PROJECT: '${PROJECT_ID}'
labels:
  application: notifuse
  component: telemetry
  environment: production
